<?php
    $mainCountry = $this->getMainCountry();
    $mainFlag = $mainCountry['country_code'];
    $mainStore = $mainCountry['country_name'];
    $stores = $this->getCountries();
    $numStores = count($stores);
    $i = 0;
?>
<div id="locale-wrapper" class="locale-wrapper">
    <ul id="main-locale" class="main-locale">
        <!-- each dom element should get its own line, then its more readable -->
        <li>
            <a id="main-country" href="#">
                <img src="<?php echo $this->getSkinUrl('images/flags/' . $mainFlag . '.png'); ?>" />
                <?php echo $this->__($mainStore); ?>
            </a>
        </li>
    </ul>
    <div id="locale-switcher" class="locale-switcher m-fadeOut" tabindex="1">
        <ul class="locale-list">
        <?php foreach($stores as $store) { ?> 
            <li class="locale-link">
                <a href="<?php echo $this->__($store['url']); ?>">
                    <img src="<?php echo $this->getSkinUrl() . 'images/flags/' . $store['country_code'] . '.png'; ?>" />
                    <?php echo $this->__($store['country_name']); ?>
                </a>
            </li>
        <?php  } ?>
        </ul>
    </div>
</div>
 <script type="text/javascript">
    (function() {
        var mainCountry = document.getElementById('main-country');
        var switcher = document.getElementById('locale-switcher');
        var header = document.getElementById('header');
        var button;
        var iOS = /iPad|iPhone|iPod|Android/.test(navigator.userAgent) && !window.MSStream;

        function hasClass(elem, name) {
            return (elem.className.indexOf(name) != -1) ? true : false;
        }

        function addClass(elem, name) {
            if (hasClass(elem, name) == false) {
                elem.className += (' ' + name);
            }
        }

        function removeClass(elem, name) {
            if (hasClass(elem, name) == true) {
                elem.className = elem.className.replace(new RegExp('(\\s|^)' + name + '(\\s|$)'), ' ').replace(/^\s+|\s+$/g, '');
            }
        }

        this.onMouseOver = function(event) {
            event.preventDefault();
            event.stopPropagation();

            addClass(switcher, 'm-fadeIn');
            removeClass(switcher, 'm-fadeOut');
            //document.body.onpointerenter = this.onMouseOut.bind(this);
        }

        this.onMouseOut = function(event) {
            event.preventDefault();
            event.stopPropagation();
            
            addClass(switcher, 'm-fadeOut');
            removeClass(switcher, 'm-fadeIn');
            //mainCountry.addEventListener('touchstart', this.onMouseOver.bind(this), false);
        }

        if(iOS) {
            button = document.createElement('button');
            button.id = "close-locale";
            button.innerText = "X";
            button.style.float = 'right';
            button.style.backgroundColor = '#f0f0f0';
            button.style.border = 'none';
            button.style.boxShadow = 'none';
            button.style.outline = 'none';
            switcher.insertBefore(button, switcher.firstChild);
            button.addEventListener('touchstart', function(e) {
                e.preventDefault();
                addClass(switcher, 'm-fadeOut');
                removeClass(switcher, 'm-fadeIn');
                mainCountry.addEventListener('touchstart', function(ev) {addClass(switcher, 'm-fadeIn'); removeClass(switcher, 'm-fadeOut')}, false);
            }, false);
            
        }

        mainCountry.addEventListener('mouseover', this.onMouseOver.bind(this), false);
        switcher.addEventListener('mouseleave', this.onMouseOut.bind(this), false);
        //switcher.addEventListener('touchstart', this.onMouseOver.bind(this), false);

    })();
</script>
           
